---
name: ci_deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - run: |
          make application/test/unit
          make application/verify
          make application/build
          make docker/build
          make docker/push
          make infrastructure/deploy